### ISSUE TITLE
Pybricks BLE minor documentation issues

### ISSUE THREAD

**Issue by fkleon** [pybricks/technical-info#11]
First of all thanks for providing great technical documentation, and fairly easy to read reference implementations!

I noticed the following issues in the docs:

1.  In the data format section on [Pybricks Bluetooth Low Energy Broadcast/Observe](https://github.com/pybricks/technical-info/blob/e3276340926725fc428fe3d6888c907118dfeb48/pybricks-ble-broadcast-observe.md#data-format), the type and length packing is described as:

> The type and length are packed into one byte using `(type << 3) | (length & 0x1F).

Looking at the reference implementation and experimenting with this, I think this should be a left shift by 5 bits instead, to read:

> The type and length are packed into one byte using `(type << 5) | (length & 0x1F)`.

(There's also a missing backtick so it doesn't format correctly).

2. The main README could use a bullet point/link to `pybricks-ble-broadcast-observe.md` and `pybricks-ble-profile.md`, I initially missed the BLE documentation just scanning it.
3. The link to the BLE broadast/observe spec from the [Pybricks Bluetooth Low Energy Profile
](https://github.com/pybricks/technical-info/blob/e3276340926725fc428fe3d6888c907118dfeb48/pybricks-ble-profile.md) is not working. It points to a folder not the markdown file:

> Also see [Pybricks Bluetooth Low Energy Broadcast/Observe](https://github.com/pybricks/technical-info/blob/master/pybricks-ble-broadcast-observe).

**Comment by dlech** [comment]
Thanks for pointing these out. Feel free to make a pull request to fix these.
